# Overall play time, across all roles.
# This tracker must exist, it is used directly by PlayTimeTrackingManager
- type: playTimeTracker
  id: Overall

# Jobs
- type: playTimeTracker
  id: JobLibrarian

- type: playTimeTracker
  id: JobDirector

- type: playTimeTracker
  id: JobHeadOfPersonnel

- type: playTimeTracker
  id: JobEthics

- type: playTimeTracker
  id: JobPassenger

- type: playTimeTracker
  id: JobChemist

- type: playTimeTracker
  id: JobContainmentSpecialist

- type: playTimeTracker
  id: JobResearchAssistant

- type: playTimeTracker
  id: JobScientist

- type: playTimeTracker
  id: JobFieldAgent

- type: playTimeTracker
  id: JobSecurityAgent

- type: playTimeTracker
  id: JobCommander

- type: playTimeTracker
  id: JobChef

- type: playTimeTracker
  id: JobDClass

- type: playTimeTracker
  id: JobMedicalDoctor

- type: playTimeTracker
  id: JobPsychologist

- type: playTimeTracker
  id: JobSupplyManager

- type: playTimeTracker
  id: JobTechnician
