- type: job
  id: ContainmentSpecialist
  name: job-name-scientist
  startingGear: ContainmentSpecialistGear
  departments:
  - Science
  icon: "Scientist"
  supervisors: job-supervisors-hop
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ContainmentSpecialist
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
